  - name: WebExtPublish: Firefox
  # You may pin to the exact commit or the version.
  # uses: maoserr/firefox_extension_publish@1e1144f073dbdc5cc9c5c0e601823d4825e48455
  uses: maoserr/firefox_extension_publish@v1.0.4
  with:
    # Extension ID.
    firefox_extension_id: {724d1c91-059e-4392-8478-494513fc8241}
    # API key from Mozilla
    api_key: user:17905501:361
    # API secret from Mozilla
    api_secret: ec47357b521e61a93425523308950be1fc60524065bdee87df43be6302b5aad4
    # Zip file for firefox extension
    file: domhelper.xpi
          
